name: Cypress

on:
  push:
    paths: ['cypress/**']
  pull_request:
    paths: ['cypress/**']
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4   
    - name: Execute Cypress
      uses: cypress-io/github-action@v6
      with:
        working-directory: cypress
        browser: chrome
    - name: Store screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-screenshots
        path: cypress/cypress/screenshots/**/*.png
        retention-days: 30
