name: Playwright

on:
  push:
    paths: ['playwright/**']
  pull_request:
    paths: ['playwright/**']
  workflow_dispatch:

jobs:
  playwright-js:
    name: JavaScript
    uses: ./.github/workflows/playwright-js.yml
