name: Playwright

on:
  push:
    paths: ['playwright/**']
  pull_request:
    paths: ['playwright/**']
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install browsers
      run: npx playwright install --with-deps
    - name: Install dependencies and run tests
      run: |
        cd playwright
        npm ci
        npx playwright test --project=chromium
    - name: Store screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-screenshots
        path: playwright/*.png
        retention-days: 30
    - name: Store report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright/playwright-report/
        retention-days: 30
