name: Playwright Java

on:
  workflow_call:
  workflow_dispatch:

env:
  DISPLAY: :99

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v5
    - name: Set up Java
      uses: actions/setup-java@v5.0.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb $DISPLAY &
    - name: Run tests
      run: |
        cd playwright/java
        mvn -B test
        mvn allure:report
    - name: Store screenshots
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: playwright-java-screenshots
        path: playwright/java/*.png
        retention-days: 30
    - name: Store traces
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: playwright-java-traces
        path: playwright/java/*.zip
        retention-days: 30
    - name: Store recordings
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: playwright-java-recordings
        path: playwright/java/*.webm
        retention-days: 30
    - name: Store reports
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: playwright-java-reports
        path: playwright/java/target/site/allure-maven-plugin
        retention-days: 30
