name: Playwright

on:
  push:
    paths: ['playwright/**']
  pull_request:
    paths: ['playwright/**']
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd playwright
        npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        cd playwright
        npx playwright test
    - name: Store screenshot
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-screenshot
        path: playwright/*.png
        retention-days: 30
    - name: Store report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright/playwright-report/
        retention-days: 30
