name: Playwright

on:
  push:
    paths: ['playwright/**']
  pull_request:
    paths: ['playwright/**']
  workflow_dispatch:

jobs:
  playwright-js:
    name: Playwright JavaScript
    uses: ./.github/workflows/playwright-js.yml

  playwright-java:
    name: Playwright Java
    uses: ./.github/workflows/playwright-java.yml
