name: Puppeteer

on:
  push:
    paths: ['puppeteer/**']
  pull_request:
    paths: ['puppeteer/**']
  workflow_dispatch:

env:
  DISPLAY: :99

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb $DISPLAY &
    - name: Install dependencies and run Puppeteer test
      run: |
        cd puppeteer
        npm install
        npm test
    - name: Store screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: puppeteer-screenshots
        path: puppeteer/*.png
        retention-days: 30
